export enum DASHBOARD_PAGES {
    HOME = 'HOME',
    GENERATE_REPORT = 'GENERATE_REPORT',
    USER_MANAGEMENT = 'USER_MANAGEMENT',
    SETTINGS = 'SETTINGS',
    GL_MAPPING = 'GL_MAPPING',
    CUSTOM_DATA = 'CUSTOM_DATA',
    ADJUSTMENTS = 'ADJUSTMENTS',
}
