import { Report, ReportData } from "../../interfaces";

export const mockData: ReportData[] = [
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_1",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR2",
        bank_code: "00405",
        return_code: "RETURN_2",
        return_name: "MCFPR2",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_3",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_4",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_5",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_6",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_7",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_8",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_9",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_10",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_11",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_12",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_13",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_14",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_15",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_16",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_17",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_18",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_19",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_20",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_21",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_22",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_23",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_24",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_25",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_26",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_27",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_28",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_29",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_30",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_31",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_32",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_33",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_34",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_35",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_36",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_37",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_38",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_39",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_40",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_41",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_42",
        return_name: "MCFPR1",
    },
    {
        serial_number: 0,
        bank_name: "NIGERIAN EXPORT IMPORT BANK (NEXIM)",
        sheet_number: "MCFPR1",
        bank_code: "00405",
        return_code: "RETURN_43",
        return_name: "MCFPR1",
    },
];
