export * from './pagination.interface';
// export * from './tableColumn.interface';
export * from './report.interface';
export * from './userManagement.interface';
export * from './config.interface';
export * from './requestOptions.interface';
export * from './paginated-table.interface';
export * from './gl.interface';
export * from './custom-data.interface';
export * from './adjustment.interface';
